# Generated by Django 4.2 on 2025-03-27 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='serializedinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='adjustmentreason',
            name='org_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fulfillmentlocation',
            name='org_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventory',
            name='org_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='org_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serializedinventory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serializedinventory',
            name='org_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serializedinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adjustmentreason',
            name='name',
            field=models.CharField(help_text="Short name for the reason (e.g., 'Cycle Count Discrepancy')", max_length=100),
        ),
        migrations.AlterField(
            model_name='fulfillmentlocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fulfillmentlocation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='adjustmentreason',
            unique_together={('name', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='fulfillmentlocation',
            unique_together={('name', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'location', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('product', 'location', 'lot_number', 'org_id')},
        ),
        migrations.AlterUniqueTogether(
            name='serializedinventory',
            unique_together={('product', 'serial_number', 'org_id')},
        ),
    ]
